import localFont from "next/font/local";
import "./globals.css";
import { Nav } from "@/components/nav";
import { ThemeProvider } from "@/components/theme-provider";
import CustomBackground from "@/components/backgroundShap";
import LenisCom from "@/components/lenis";

const Acumin = localFont({
	src: "./fonts/Acumin-RPro.otf",
	variable: "--font-acumin",
	weight: "100 900",
});
export const Campton = localFont({
	src: "./fonts/CamptonBold.otf",
	variable: "--font-campton",
	weight: "900",
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={` ${Acumin.className} antialiased`}>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<CustomBackground />
					<Nav />
					<LenisCom>{children}</LenisCom>
					{/* {children} */}
				</ThemeProvider>
			</body>
		</html>
	);
}
